# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('wake-up-radio-example', ['wake-up-radio'])
    obj.source = 'wake-up-radio-example.cc'
    obj.cxxflags = ['-g']


